### ISSUE TITLE
[docs request] Indicate which scopes are required for a Personal Access Token

### ISSUE THREAD

**Issue by skaematik** [realyze/pr-train#13]
The docs mention `Pre-requisite: Create a ${HOME}/.pr-train file with a single line which is your GH access token (you can create one here).`

It would be great to specify which scopes are required. :) 

You can see the list of scopes at: https://github.com/settings/tokens/new

Thanks!

**Comment by realyze** [comment]
Ah, great suggestion, thanks! Do you think you could open a PR? :-P

**Comment by skaematik** [comment]
Ah yep, can do, I'll have a look at which scopes you're using... 😬

**Comment by realyze** [comment]
I think we need `Full control of private repositories` (because GH _still_ doesn't have read-only / create-pr only scopes).
