### ISSUE TITLE
[feature request] Preserve description of existing PR

### ISSUE THREAD

**Issue by upsuper** [realyze/pr-train#7]
It seems currently `pr-train -p --create-prs` would override the whole description of existing PR with the PR list. It's pretty undesirable. It would be helpful if it just update (or insert) the PR list but not touch the existing content.

**Comment by realyze** [comment]
Hey @upsuper as of 2.2.0 `git pr-train --create-prs` preserves the title and description and only updates the table of contents.

**Comment by upsuper** [comment]
Oh that's a great news! When would that get published? It's still 2.1.2 on npm.

**Comment by realyze** [comment]
Published now (2.2.1). 👍 I thought I had already but looks like I haven't. Oh well.
